### PR TITLE
Update Carbon CSS

### PR DESCRIPTION
**Pull request by sayzlim**
Matches the ad design with the sidebar styles. See the screenshot here:

### CODE REVIEW

**Comment by jedmao** [comment]
Thanks!

**Comment by jedmao** [comment]
I just noticed the ads don't show up on a mobile device. Any ideas there?

**Comment by jedmao** [comment]
I suppose this is the kind of site that is way less likely to be hit on a mobile device, as people will be writing code.

**Comment by sayzlim** [comment]
Agree. We track the impressions on every API request, but most people will visit the site on the desktop. Let’s consider the impressions from mobile browser as additional revenue for the project.

Thanks for merging the PR @jedmao!

**Pull request merged**
