### PR TITLE
Add neovim

### PR DESCRIPTION
**Pull request by SvartaHjarta**
Addresses #172

### CODE REVIEW

**Comment by xuhdev** [comment]
We usually repaint the logo with a hand-draw style. Usually someone volunteered to repaint -- recently almost always @Pittan (thanks!) --  but certainly no one is obliged to do the repainting. Would you be able to apply some style transformer to the logo to alter it to a different style? Thanks!

**Comment by SvartaHjarta** [comment]
I'll look into it.

**Comment by TheBlckbird** [comment]
Bildschirmfoto 2023-08-16 um 16 20 35
I tried

**Comment by xuhdev** [comment]
@TheBlckbird It looks awesome, thank you! Would you like to open a PR for the website? Otherwise I can open the PR.

**Comment by TheBlckbird** [comment]
@xuhdev I'll open a PR

**Comment by TheBlckbird** [comment]
@xuhdev See #173

**Pull request closed without merging**
