### PR TITLE
Markup improvements

### PR DESCRIPTION
**Pull request by Zearin**
* improvements center on semantic markup
* markup now validates at http://validator.w3.org

### CODE REVIEW

**Comment by Zearin** [comment]
@coliff @treyhunner ping

**Comment by Zearin** [comment]
Ping

**Comment by xuhdev** [comment]
ping @treyhunner

**Comment by treyhunner** [comment]
Thanks @Zearin!  Sorry for the slow response.

**Comment by Zearin** [comment]
@treyhunner np! Glad to help. ☻

**Pull request merged**
