### PR TITLE
Update Jetbrains IDE logos

### PR DESCRIPTION
**Pull request by Pittan**
Update IDE logo for JetBrains IDEs.

### CODE REVIEW

**Comment by xuhdev** [comment]
@treyhunner

**Comment by treyhunner** [comment]
👍 looks good to me! Thanks @Pittan! 😄

**Comment by Pittan** [comment]
Thank you 🤗

**Comment by ineptcat** [comment]
those logos look awesome @Pittan ! 
we should update the contributions tag at the bottom of the site for proper crediting.

**Pull request merged**
