### PR TITLE
STYLE | Switched to system font stack

### PR DESCRIPTION
**Pull request by bennias**
Switched from **Arial** > **System Font Stack**.

### CODE REVIEW

**Comment by ffes** [comment]
I have no idea as well why we should do this. And the fonts seems very specific to Apple to me

**Comment by bennias** [comment]
Sure! Take a look at: 
https://css-tricks.com/snippets/css/system-font-stack/

**Comment by xuhdev** [comment]
It seems to make sense to use system font, but why `-apple-system`? What about other OSes?

**Comment by bennias** [comment]
@xuhdev Well, I think the order of the system fonts doesn't affect the functionality. I just took the standard which is used on other websites like Medium or GitHub. Just take a look at the CSS on this page.

**Comment by bennias** [comment]
So, if you see no need for this - let's close it.

**Comment by xuhdev** [comment]
@bennias Sorry I didn't mean that. I think the whole thing makes sense, it's just some detail that I was not fully aware of. I personally think this is ready to merge.

**Pull request closed without merging**
