### PR TITLE
Add Komodo logo

### PR DESCRIPTION
**Pull request by treyhunner**
Before this can be merged:
- Komodo/KomodoEdit#271 must be resolved
- The URL for the link needs to be updated appropriately

### CODE REVIEW

**Comment by treyhunner** [comment]
Screenshot of what it will look like:

selection_428

**Comment by Naatan** [comment]
Awesome! +Motivation :p

**Comment by Naatan** [comment]
Fyi just pushed native support for Komodo - https://github.com/Komodo/KomodoEdit/commit/1a1a9047d64cd05f6eb4f8726d68032dad3cfea5

It will be available in Komodo 9.2 (our next release) and the nightlies.

I'll also be submitting it to our resources section later this week, so people can install it as an addon if they dont want to wait - http://komodoide.com/resources/

**Comment by treyhunner** [comment]
@Naatan that's great news!

Please update me when it's in the resources section so we can link to it from our homepage.  Then once 9.2 is released I'll move the icon to our "No plugin necessary" section.

**Comment by Naatan** [comment]
Addon submitted and available: http://komodoide.com/resources/addons/komodo--editorconfig/

**Comment by treyhunner** [comment]
Logo live! :smile:

**Pull request merged**
