### PR TITLE
Add a Jekyll-based blog

### LINKED ISSUE #49: Make a blog for announcements
As discussed in #48 by [Hong](https://github.com/editorconfig/editorconfig.github.com/pull/48#issuecomment-110113975).

### PR DESCRIPTION
**Pull request by ffes**
Closes #49 

This adds a blog to the website. I used Jekyll to create the posts. See the [Jekyll docs](https://jekyllrb.com/docs/posts/) for more information how to add new posts or use drafts.

I have written two quite simple posts. One announcing the blog and the other one announcing the new version of the Notepad++ plugin

### CODE REVIEW

**Comment by ffes** [comment]
I just pushed two additional commits.
Any changes anyone could take a look at this?

cc @xuhdev @treyhunner

**Comment by xuhdev** [comment]
Thanks! I'll look into this tomorrow and give my comments.

**Comment by xuhdev** [comment]
It looks good to me, except for that it's a bit weird to have the "Blog added" post not the earliest post. Besides that, I think it's ready to be merged. @treyhunner What do you think?

**Comment by ffes** [comment]
I understand your point about the date of the "Blog added" post. I added two posts (in the original PR) to have some content. Since there is a new release of the N++ plugin after this PR was opened, the first post (announcing N++ plugin v0.3.0) can be deleted anyway.

**Comment by treyhunner** [comment]
@ffes thanks for the work you've put into this!

I have a couple stylistic suggestions for the sidebar (see screenshot below), but I'll avoid bike shedding over those. I can make those changes after we've merged this.
selection_797

---

As for the blog itself:

- When should posts be written?
- Who will write posts?
- Should we encourage plugin authors to write posts announcing new features in their plugins?

I can help edit posts, but I don't think I'll be authoring many myself.

**Comment by ffes** [comment]
I like the stylistic changes. The reason I choose the slightly indented layout was because that is what the current layout is. But I agree this definitely looks better. And I am not a web designer, so layout adjustments will almost certainly be an improvement over what I have done.

> When should posts be written?
> Who will write posts?
> Should we encourage plugin authors to write posts announcing new features in their plugins?

In #48 @xuhdev states that a blog would be great for announcements. I think (being "a new guy" to this project) the most announcements would be about plug-in releases. So I think that will be the main content of the blog. And writing a blog post is not too difficult: copy an existing, write out the new features and create a PR. It should be relative little work for plug-in authors to create a blog post. The advantage for them is that their works get noticed.

Some final reviewing on the English by a native speaker (which I'm not) would be great.

**Comment by xuhdev** [comment]
I agree with @ffes . The blog would be the best place (IMO) to make announcements. It can also be used to make other project-wide announcements. If @treyhunner is OK with it, either of us can merge the PR.

**Comment by xuhdev** [comment]
@treyhunner Do you have any problem with merging the PR?

**Comment by xuhdev** [comment]
@ffes Before merging, can we remove the Notepad++ 0.3.0 announcement?

**Comment by xuhdev** [comment]
Or make the blog anouncement earlier...

**Comment by ffes** [comment]
I just remove the N++ 0.3.0 post. So now "Blog added" is the first one.

**Comment by xuhdev** [comment]
Thanks! I'll merge it and make an announcement in the mailing list for all the plugin authors to make announcement on the website when they make new releases.

**Comment by ffes** [comment]
Maybe @andreynering could be asked to write a post about the new core-go he release a couple of days ago.

**Comment by andreynering** [comment]
@ffes I'd happly do that, if you guys are OK with that.

If https://github.com/gogits/gogs/pull/3241 got merged, we could together announce the Gogs support.

**Pull request merged**
