### PR TITLE
Add separate section for editors with native support

### PR DESCRIPTION
**Pull request by treyhunner**

### CODE REVIEW

**Comment by treyhunner** [comment]
Separate section:

selection_372

**Comment by xuhdev** [comment]
I think it looks good

**Comment by jedmao** [comment]
:+1:

**Comment by denofevil** [comment]
Looks good. One correction: AppCode, PhpStorm, Pycharm should be in second section.
And probably we can change the links for ones that require plugin to point at plugin website directly (https://plugins.jetbrains.com/plugin/7294)

**Comment by treyhunner** [comment]
I moved those three IDEs to the second section and changed the links for them.

@denofevil does CLion support EditorConfig by default?

**Comment by denofevil** [comment]
No, plugin needed

**Comment by treyhunner** [comment]
It's now split into two sections.  Thanks all for the feedback.

**Pull request merged**
