### PR TITLE
Add Eclipse logo

### PR DESCRIPTION
**Pull request by treyhunner**
Before this can be merged, the link will need to be updated to point to a working Eclipse EditorConfig plugin.

There are currently two under-development Eclipse EditorConfig plugins:

- [ncjones/editorconfig-eclipse](https://github.com/ncjones/editorconfig-eclipse) by @ncjones
- [danielgcf/editorconfig-eclipse](https://github.com/danielgcf/editorconfig-eclipse) by @danielgcf

### CODE REVIEW

**Comment by ctjhoa** [comment]
@treyhunner Considering [this discussion](https://github.com/ncjones/editorconfig-eclipse/issues/4) and the date of the last commit of [danielgcf/editorconfig-eclipse](https://github.com/danielgcf/editorconfig-eclipse) I think decision to add [ncjones/editorconfig-eclipse](https://github.com/ncjones/editorconfig-eclipse) is acceptable.

It's very confusing to not have a eclipse plugin directly in the website.

**Comment by treyhunner** [comment]
@ctjhoa I agree.

@ncjones do you have any objection to adding your plugin on the website?

**Comment by ncjones** [comment]
@treyhunner Fine by me.

**Comment by treyhunner** [comment]
@ncjones do you have a Twitter handle you would like me to use when announcing this plugin?

**Comment by ncjones** [comment]
No, I don't use Twitter.

**Pull request merged**
