### PR TITLE
Add MonoDevelop icon

### PR DESCRIPTION
**Pull request by Pittan**
For https://github.com/editorconfig/editorconfig.github.com/issues/85

### CODE REVIEW

**Comment by Pittan** [comment]
Sorry to be late! Please review :bow: @xuhdev

**Comment by Mpdreamz** [comment]
rejoice! :heart:

**Comment by Pittan** [comment]
is there any updates? > @xuhdev

**Comment by xuhdev** [comment]
Sorry for the delay. Let me add it now :)

**Pull request merged**
