### PR TITLE
Add VSCodium

### PR DESCRIPTION
**Pull request by kmk3**
"binary releases of VS Code without MS branding/telemetry/licensing"

* Homepage: https://vscodium.com/
* Source Code: https://github.com/VSCodium/vscodium

Since Visual Studio Code is present, might as well add the Free/Libre
version of it.

Logo taken from:
https://github.com/VSCodium/vscodium/blob/cb5e22e005a1e3373f5e0ee9bb79d182587db2df/src/resources/linux/code.png

### CODE REVIEW

**Comment by Pittan** [comment]
@kmk3 
Thank you for your contribution!  
As you already seen on editorconfig.com, we are using hand-written style logo.
Using the original logo maybe okay, but creating a hand-written style logo will fit in with rest of the logos.

Could you add the image on your PR? If you not in hurry, I can create the image and put it on this PR's comment.

@xuhdev 
what do you think about this?

**Comment by xuhdev** [comment]
Yeah I agree with @Pittan . @kmk3 Could you share the logo image? We will redraw the logo to fit to the style of the rest of the page (thanks to @Pittan and Kat for the conversion)

**Comment by Pittan** [comment]
@xuhdev I think the image is attached to this PR.

**Comment by kmk3** [comment]
@Pittan commented yesterday:

> @kmk3
>
> Thank you for your contribution!

No problem.

> As you already seen on editorconfig.com, we are using hand-written style
> logo.

Funny thing; I had noticed that in the past, but this time I was just looking
at the vim and vscode logos on the site and thought that they looked pretty
similar to the originals (or that they were the originals), so I just went and
grabbed the official vscodium logo.

> Using the original logo maybe okay, but creating a hand-written style logo
> will fit in with rest of the logos.

Indeed, and I like the hand-written style.

> Could you add the image on your PR? If you not in hurry, I can create the
> image and put it on this PR's comment.

I have no drawing skills and there is no hurry, so feel free to do that :p

By the way, what are the tools used to create these logos?

**Comment by Pittan** [comment]
@kmk3 
> I have no drawing skills and there is no hurry, so feel free to do that :p
>
> By the way, what are the tools used to create these logos?

Thanks! I'll create a logo image and attach to this PR's comment later today.
I'm using Photoshop + iPad Sidecar to redraw logos. (Maybe too much for this kind of task :))

**Comment by Pittan** [comment]
@kmk3 
Sorry to be late 🙇 
Here's the hand-written version of VSCodium logo.
vscodium

**Comment by Pittan** [comment]
Wait... may be we should add a border around the logo (It will blend to the background but we should avoid it)
Just a sec...

**Comment by Pittan** [comment]
https://github.com/editorconfig/editorconfig.github.com/pull/141#issuecomment-922500893
Updated image!

**Comment by xuhdev** [comment]
Awesome! @Pittan Would you like me to add the logo in a separate PR or would you prefer opening a PR by yourself?

**Comment by Pittan** [comment]
@xuhdev 
Thank you! I was thinking that @kmk3 will swap this image to the image included in this PR.

**Comment by kmk3** [comment]
@Pittan commented [on Sep 19](https://github.com/editorconfig/editorconfig.github.com/pull/141#issuecomment-922500893):

> @kmk3
> Sorry to be late bow

It's alright.

> Here's the hand-written version of VSCodium logo.
> vscodium

Nice, it looks very close to the original.

@Pittan commented [on Sep 20](https://github.com/editorconfig/editorconfig.github.com/pull/141#issuecomment-922592671):

> I was thinking that @kmk3 will swap this image to the image included in this
> PR.

My thought as well; I've swapped and force-pushed.  I put the credits on the
commit message.

**Comment by xuhdev** [comment]
Thanks @kmk3 . Could you add the following to your git message? This should automatically credit @Pittan 

    Co-authored-by: pittan <amon.keishima@pittankopta.net>

**Comment by kmk3** [comment]
@xuhdev commented [on Sep 20](https://github.com/editorconfig/editorconfig.github.com/pull/141#issuecomment-923244583):

> Thanks @kmk3 . Could you add the following to your git message? This should
> automatically credit @Pittan (replace `AT` and `DOT` with `@` and `.`)
> 
> ```
> Co-authored-by: pittan <amon.keishima AT pittankopta DOT net>
> ```

Sure, but are you certain that the above is correct?  On @Pittan's latest
non-merge commit (commit 3e54962 ("Add GitLab (#133)")), the author is listed
as:

```
Amon Keishima <pittan AT pittankopta DOT net>
```

**Comment by Pittan** [comment]
@kmk3 
`pittan at pittankopta dot net` is an alias to `amon.keishima at ...` so it doesn't matter which one I / you choose :)

**Comment by kmk3** [comment]
@Pittan commented [on Oct 2](https://github.com/editorconfig/editorconfig.github.com/pull/141#issuecomment-932708678):

> @kmk3 `pittan at pittankopta dot net` is an alias to `amon.keishima at ...`
> so it doesn't matter which one I / you choose :)

Ah, good to know.

@kmk3 commented [on Sep 21](https://github.com/editorconfig/editorconfig.github.com/pull/141#issuecomment-923819675):

> @xuhdev commented [on Sep 20](https://github.com/editorconfig/editorconfig.github.com/pull/141#issuecomment-923244583):
> 
> > Thanks @kmk3 . Could you add the following to your git message? This should
> > automatically credit @Pittan (replace `AT` and `DOT` with `@` and `.`)
> >
> > ```
> > Co-authored-by: pittan <amon.keishima AT pittankopta DOT net>
> > ```
> 
> Sure, but are you certain that the above is correct? On @Pittan's latest
> non-merge commit (commit
> [3e54962](https://github.com/editorconfig/editorconfig.github.com/commit/3e54962e92f8485fb687fbd3d8db14deb64faa9c)
> ("Add GitLab (#133)")), the author is listed as:
> 
> ```
> Amon Keishima <pittan AT pittankopta DOT net>
> ```

Now I noticed that I was checking the commits on this PR branch rather than on
master (sorry about that).  @Pittan's latest commit on master is 223cc0d ("Add
Pluma"), so your original suggestion appears to be the more fitting one indeed.

I went with that one and force-pushed.

**Review by xuhdev — APPROVED** [review]
Awesome! Thanks for the PR and thanks to @Pittan again for the logo!

**Pull request merged**
